import fs from 'fs';
import path from 'path';
import fetch from 'node-fetch';
import { CreateServerPayload, ServerLoader } from '@warden/shared';

export class ServerInstaller {
  public static async installServer(
    targetDir: string,
    payload: CreateServerPayload
  ): Promise<{ jarFileName: string; loader: ServerLoader; mcVersion: string }> {
    // Ensure target directory exists
    await fs.promises.mkdir(targetDir, { recursive: true });
    await fs.promises.mkdir(path.join(targetDir, 'mods'), { recursive: true });
    await fs.promises.mkdir(path.join(targetDir, 'plugins'), { recursive: true });

    let jarFileName = 'server.jar';

    switch (payload.loader) {
      case 'paper': {
        jarFileName = await this.installPaper(targetDir, payload.mcVersion);
        break;
      }
      case 'purpur': {
        jarFileName = await this.installPurpur(targetDir, payload.mcVersion);
        break;
      }
      case 'fabric': {
        jarFileName = await this.installFabric(targetDir, payload.mcVersion, payload.loaderVersion);
        break;
      }
      case 'quilt': {
        jarFileName = await this.installQuilt(targetDir, payload.mcVersion, payload.loaderVersion);
        break;
      }
      case 'vanilla':
      default: {
        jarFileName = await this.installVanilla(targetDir, payload.mcVersion);
        break;
      }
    }

    // EULA acceptance is handled by the frontend via popup modal
    // Do NOT auto-accept here

    // Create default server.properties if not already existing
    const propsPath = path.join(targetDir, 'server.properties');
    if (!fs.existsSync(propsPath)) {
      const defaultPort = payload.port || 25601;
      const defaultProps = [
        '# Minecraft server properties generated by Warden',
        `server-port=${defaultPort}`,
        `motd=${payload.name} | Managed by Warden`,
        'gamemode=survival',
        'difficulty=normal',
        'pvp=true',
        'hardcore=false',
        'max-players=20',
        'online-mode=true',
        'enable-command-block=true',
        'view-distance=10',
        'simulation-distance=10',
        'allow-flight=false',
        'spawn-protection=16',
      ].join('\n');
      await fs.promises.writeFile(propsPath, `${defaultProps}\n`, 'utf8');
    }

    return {
      jarFileName,
      loader: payload.loader,
      mcVersion: payload.mcVersion,
    };
  }

  // 1. PaperMC Installer
  private static async installPaper(targetDir: string, version: string): Promise<string> {
    // Try Paper v3 (fill.papermc.io) API first
    try {
      const v3BuildsUrl = `https://fill.papermc.io/v3/projects/paper/versions/${version}/builds`;
      const res = await fetch(v3BuildsUrl);
      if (res.ok) {
        const builds = (await res.json()) as any[];
        if (Array.isArray(builds) && builds.length > 0) {
          const latestBuild = builds[builds.length - 1];
          const downloadObj =
            latestBuild.downloads?.['server:default'] ||
            latestBuild.downloads?.application ||
            latestBuild.downloads?.['server:mojang'];
          if (downloadObj?.url && downloadObj?.name) {
            const jarDest = path.join(targetDir, downloadObj.name);
            await this.downloadFile(downloadObj.url, jarDest);
            return downloadObj.name;
          }
        }
      }
    } catch {}

    // Fallback to Paper v2 API
    const versionUrl = `https://api.papermc.io/v2/projects/paper/versions/${version}`;
    const res = await fetch(versionUrl);
    if (!res.ok) {
      throw new Error(`Failed to fetch Paper version metadata for ${version} (HTTP ${res.status})`);
    }
    const data: any = await res.json();
    const builds: number[] = data.builds || [];
    if (builds.length === 0) {
      throw new Error(`No builds found for Paper version ${version}`);
    }
    const latestBuild = builds[builds.length - 1];

    const buildUrl = `https://api.papermc.io/v2/projects/paper/versions/${version}/builds/${latestBuild}`;
    const buildRes = await fetch(buildUrl);
    if (!buildRes.ok) {
      throw new Error(`Failed to fetch Paper build ${latestBuild}`);
    }
    const buildData: any = await buildRes.json();
    const downloadName = buildData.downloads?.application?.name || `paper-${version}-${latestBuild}.jar`;

    const downloadUrl = `https://api.papermc.io/v2/projects/paper/versions/${version}/builds/${latestBuild}/downloads/${downloadName}`;
    const jarDest = path.join(targetDir, downloadName);

    await this.downloadFile(downloadUrl, jarDest);
    return downloadName;
  }

  // 2. Purpur Installer
  private static async installPurpur(targetDir: string, version: string): Promise<string> {
    const downloadUrl = `https://api.purpurmc.org/v2/purpur/${version}/latest/download`;
    const jarName = `purpur-${version}.jar`;
    const jarDest = path.join(targetDir, jarName);

    await this.downloadFile(downloadUrl, jarDest);
    return jarName;
  }

  // 3. Fabric Installer
  private static async installFabric(
    targetDir: string,
    gameVersion: string,
    loaderVersion?: string
  ): Promise<string> {
    // If loaderVersion not provided, fetch the latest stable loader from Fabric Meta API
    let selectedLoader = loaderVersion;
    if (!selectedLoader) {
      const loaderMetaRes = await fetch('https://meta.fabricmc.net/v2/versions/loader');
      if (loaderMetaRes.ok) {
        const loaders: any = await loaderMetaRes.json();
        const stableLoader = loaders.find((l: any) => l.stable) || loaders[0];
        selectedLoader = stableLoader?.version || '0.16.9';
      } else {
        selectedLoader = '0.16.9';
      }
    }

    // Fetch latest installer version
    let installerVersion = '1.0.1';
    const installerMetaRes = await fetch('https://meta.fabricmc.net/v2/versions/installer');
    if (installerMetaRes.ok) {
      const installers: any = await installerMetaRes.json();
      const stableInstaller = installers.find((i: any) => i.stable) || installers[0];
      installerVersion = stableInstaller?.version || '1.0.1';
    }

    // Direct server launcher jar URL from Fabric Meta
    const downloadUrl = `https://meta.fabricmc.net/v2/versions/loader/${gameVersion}/${selectedLoader}/${installerVersion}/server/jar`;
    const jarName = `fabric-server-mc.${gameVersion}-loader.${selectedLoader}-launcher.${installerVersion}.jar`;
    const jarDest = path.join(targetDir, jarName);

    await this.downloadFile(downloadUrl, jarDest);
    return jarName;
  }

  // 4. Quilt Installer
  private static async installQuilt(
    targetDir: string,
    gameVersion: string,
    loaderVersion?: string
  ): Promise<string> {
    let selectedLoader = loaderVersion;
    if (!selectedLoader) {
      const loaderMetaRes = await fetch('https://meta.quiltmc.org/v3/versions/loader');
      if (loaderMetaRes.ok) {
        const loaders: any = await loaderMetaRes.json();
        selectedLoader = loaders[0]?.version || '0.26.4';
      } else {
        selectedLoader = '0.26.4';
      }
    }

    const downloadUrl = `https://meta.quiltmc.org/v3/versions/loader/${gameVersion}/${selectedLoader}/0.1.4/server/jar`;
    const jarName = `quilt-server-${gameVersion}.jar`;
    const jarDest = path.join(targetDir, jarName);

    await this.downloadFile(downloadUrl, jarDest);
    return jarName;
  }

  // 5. Vanilla Installer
  private static async installVanilla(targetDir: string, version: string): Promise<string> {
    const manifestRes = await fetch('https://launchermeta.mojang.com/mc/game/version_manifest_v2.json');
    if (!manifestRes.ok) {
      throw new Error(`Failed to fetch Mojang version manifest`);
    }
    const manifest: any = await manifestRes.json();
    const versionEntry = manifest.versions?.find((v: any) => v.id === version);
    if (!versionEntry) {
      throw new Error(`Minecraft version ${version} not found in Mojang manifest`);
    }

    const versionMetaRes = await fetch(versionEntry.url);
    if (!versionMetaRes.ok) {
      throw new Error(`Failed to fetch metadata for Minecraft ${version}`);
    }
    const versionMeta: any = await versionMetaRes.json();
    const serverDownloadUrl = versionMeta.downloads?.server?.url;
    if (!serverDownloadUrl) {
      throw new Error(`No server jar download available for Minecraft ${version}`);
    }

    const jarName = `minecraft_server.${version}.jar`;
    const jarDest = path.join(targetDir, jarName);

    await this.downloadFile(serverDownloadUrl, jarDest);
    return jarName;
  }

  // Helper to stream download a file with progress tracking
  private static async downloadFile(url: string, destination: string): Promise<void> {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`Failed to download from ${url} (HTTP ${res.status}: ${res.statusText})`);
    }
    const fileStream = fs.createWriteStream(destination);
    await new Promise<void>((resolve, reject) => {
      res.body?.pipe(fileStream);
      res.body?.on('error', reject);
      fileStream.on('finish', () => resolve());
      fileStream.on('error', reject);
    });
  }
}
