import os
import re
import json
import httpx
from typing import Optional, Dict, Any

class ServerInstaller:
    @staticmethod
    async def install_vanilla(target_dir: str, mc_version: str) -> str:
        os.makedirs(target_dir, exist_ok=True)
        async with httpx.AsyncClient(timeout=30.0) as client:
            manifest_res = await client.get("https://piston-meta.mojang.com/mc/game/version_manifest_v2.json")
            manifest_res.raise_for_status()
            manifest = manifest_res.json()

            version_entry = next((v for v in manifest.get("versions", []) if v.get("id") == mc_version), None)
            if not version_entry:
                raise ValueError(f"Minecraft Vanilla version '{mc_version}' not found in Mojang manifest.")

            ver_detail_res = await client.get(version_entry["url"])
            ver_detail_res.raise_for_status()
            ver_detail = ver_detail_res.json()

            server_dl = ver_detail.get("downloads", {}).get("server")
            if not server_dl or not server_dl.get("url"):
                raise ValueError(f"No server jar available for Vanilla {mc_version}.")

            jar_name = f"minecraft_server.{mc_version}.jar"
            jar_path = os.path.join(target_dir, jar_name)

            dl_res = await client.get(server_dl["url"])
            dl_res.raise_for_status()
            with open(jar_path, "wb") as f:
                f.write(dl_res.content)

            return jar_name

    @staticmethod
    async def install_paper(target_dir: str, mc_version: str) -> str:
        os.makedirs(target_dir, exist_ok=True)
        async with httpx.AsyncClient(timeout=30.0) as client:
            builds_res = await client.get(f"https://api.papermc.io/v2/projects/paper/versions/{mc_version}/builds")
            builds_res.raise_for_status()
            builds_data = builds_res.json()

            builds = builds_data.get("builds", [])
            if not builds:
                raise ValueError(f"No PaperMC builds available for version {mc_version}.")

            latest_build = builds[-1]
            build_num = latest_build["build"]
            download_name = latest_build["downloads"]["application"]["name"]

            download_url = f"https://api.papermc.io/v2/projects/paper/versions/{mc_version}/builds/{build_num}/downloads/{download_name}"
            jar_name = f"paper-{mc_version}-{build_num}.jar"
            jar_path = os.path.join(target_dir, jar_name)

            dl_res = await client.get(download_url)
            dl_res.raise_for_status()
            with open(jar_path, "wb") as f:
                f.write(dl_res.content)

            return jar_name

    @staticmethod
    async def install_purpur(target_dir: str, mc_version: str) -> str:
        os.makedirs(target_dir, exist_ok=True)
        jar_name = f"purpur-{mc_version}.jar"
        jar_path = os.path.join(target_dir, jar_name)
        async with httpx.AsyncClient(timeout=45.0) as client:
            dl_res = await client.get(f"https://api.purpurmc.org/v2/purpur/{mc_version}/latest/download")
            dl_res.raise_for_status()
            with open(jar_path, "wb") as f:
                f.write(dl_res.content)
        return jar_name

    @staticmethod
    async def install_server(target_dir: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        loader = payload.get("loader", "vanilla").lower()
        mc_version = payload.get("mcVersion", "1.21.4")

        if loader == "paper":
            jar_file = await ServerInstaller.install_paper(target_dir, mc_version)
        elif loader == "purpur":
            jar_file = await ServerInstaller.install_purpur(target_dir, mc_version)
        else:
            jar_file = await ServerInstaller.install_vanilla(target_dir, mc_version)

        # Write default server.properties if not exists
        props_path = os.path.join(target_dir, "server.properties")
        if not os.path.exists(props_path):
            port = payload.get("port", 25565)
            name = payload.get("name", "Minecraft Server")
            content = (
                "# Minecraft server properties generated by Warden\n"
                f"server-port={port}\n"
                f"motd={name} | Managed by Warden\n"
                "gamemode=survival\n"
                "difficulty=normal\n"
                "pvp=true\n"
                "hardcore=false\n"
                "max-players=20\n"
                "online-mode=true\n"
                "enable-command-block=true\n"
                "view-distance=10\n"
                "simulation-distance=10\n"
                "allow-flight=false\n"
                "spawn-protection=16\n"
            )
            with open(props_path, "w", encoding="utf-8") as f:
                f.write(content)

        return {
            "jarFileName": jar_file,
            "loader": loader,
            "mcVersion": mc_version,
        }
