import os
import re
import glob
import shutil
import zipfile
import asyncio
from typing import Dict, List, Optional, Any, Callable
from app.config import settings
from app.core.process import ServerProcess
from app.core.properties import ServerProperties
from app.core.installer import ServerInstaller

class ServerManager:
    _instance: Optional["ServerManager"] = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(ServerManager, cls).__new__(cls)
            cls._instance._init_manager()
        return cls._instance

    def _init_manager(self):
        self.processes: Dict[str, ServerProcess] = {}
        self.log_callbacks: List[Callable[[str, str], None]] = []
        self.sweep_orphaned_processes()

    def add_log_callback(self, cb: Callable[[str, str], None]):
        self.log_callbacks.append(cb)

    def _on_process_log(self, server_id: str, line: str):
        for cb in self.log_callbacks:
            try:
                cb(server_id, line)
            except Exception:
                pass

    def get_server_dir(self, server_id: str) -> str:
        d = os.path.join(settings.servers_dir, server_id)
        os.makedirs(d, exist_ok=True)
        return d

    def sweep_orphaned_processes(self):
        """Sweep all warden.pid files in /data/servers/ to kill old orphaned Java instances."""
        try:
            pattern = os.path.join(settings.servers_dir, "*", "warden.pid")
            for pid_file in glob.glob(pattern):
                try:
                    with open(pid_file, "r", encoding="utf-8") as f:
                        pid_str = f.read().strip()
                    if pid_str.isdigit():
                        pid = int(pid_str)
                        import psutil
                        if psutil.pid_exists(pid):
                            p = psutil.Process(pid)
                            if "java" in p.name().lower():
                                print(f"[Warden Sweep] Terminating orphan Java process PID {pid} from {pid_file}")
                                p.terminate()
                                try:
                                    p.wait(timeout=2)
                                except psutil.TimeoutExpired:
                                    p.kill()
                    os.remove(pid_file)
                except Exception:
                    pass
        except Exception as e:
            print(f"[Warden Sweep Error] {e}")

    def resolve_java_path(self, mc_version: Optional[str] = None) -> str:
        """Dynamically detect available OpenJDK installation."""
        if mc_version and (re.match(r"^26(\b|\.)", mc_version) or "mc.26" in mc_version.lower()):
            for path in [
                "/usr/lib/jvm/java-26-openjdk/bin/java",
                "/usr/lib/jvm/java-25-openjdk/bin/java",
            ]:
                if os.path.exists(path):
                    return path

        if mc_version and (re.match(r"^1\.2[1-9]", mc_version) or re.match(r"^1\.20\.([5-9]|\d{2})", mc_version)):
            for path in [
                "/usr/lib/jvm/java-21-openjdk/bin/java",
                "/usr/lib/jvm/java-25-openjdk/bin/java",
            ]:
                if os.path.exists(path):
                    return path

        if mc_version and re.match(r"^1\.(1[6-9]|20\.[0-4])", mc_version):
            for path in [
                "/usr/lib/jvm/java-17-openjdk/bin/java",
                "/usr/lib/jvm/java-21-openjdk/bin/java",
            ]:
                if os.path.exists(path):
                    return path

        # Fallback to highest available
        for p in [
            "/usr/lib/jvm/java-25-openjdk/bin/java",
            "/usr/lib/jvm/java-21-openjdk/bin/java",
            "/usr/lib/jvm/java-17-openjdk/bin/java",
            "/usr/bin/java",
            "java",
        ]:
            if os.path.exists(p) or p == "java":
                return p
        return "java"

    def is_eula_accepted(self, server_id: str) -> bool:
        eula_path = os.path.join(self.get_server_dir(server_id), "eula.txt")
        if not os.path.exists(eula_path):
            return False
        try:
            with open(eula_path, "r", encoding="utf-8") as f:
                return "eula=true" in f.read().lower()
        except Exception:
            return False

    def accept_eula(self, server_id: str):
        eula_path = os.path.join(self.get_server_dir(server_id), "eula.txt")
        with open(eula_path, "w", encoding="utf-8") as f:
            f.write("# Generated by Warden\neula=true\n")

    def get_server_process(self, server_id: str) -> Optional[ServerProcess]:
        return self.processes.get(server_id)

    def start_server(
        self,
        server_id: str,
        jar_file: Optional[str] = None,
        java_path: Optional[str] = None,
        min_memory: str = "1G",
        max_memory: str = "4G",
        mc_version: Optional[str] = None,
    ):
        server_dir = self.get_server_dir(server_id)

        # Check EULA
        if not self.is_eula_accepted(server_id):
            raise ValueError("EULA_NOT_ACCEPTED")

        # Find JAR file if not provided
        if not jar_file:
            jars = glob.glob(os.path.join(server_dir, "*.jar"))
            if not jars:
                raise FileNotFoundError(f"No server .jar found in {server_dir}")
            jar_file = os.path.basename(jars[0])

        final_java_path = java_path or self.resolve_java_path(mc_version)

        proc = self.processes.get(server_id)
        if not proc:
            proc = ServerProcess(
                server_id=server_id,
                server_dir=server_dir,
                jar_file=jar_file,
                java_path=final_java_path,
                min_memory=min_memory,
                max_memory=max_memory,
                on_log=self._on_process_log,
            )
            self.processes[server_id] = proc
        else:
            proc.jar_file = jar_file
            proc.java_path = final_java_path
            proc.min_memory = min_memory
            proc.max_memory = max_memory

        proc.start()

    def stop_server(self, server_id: str):
        proc = self.processes.get(server_id)
        if proc:
            proc.stop()

    def restart_server(self, server_id: str):
        proc = self.processes.get(server_id)
        if proc:
            proc.restart()

    def kill_server(self, server_id: str):
        proc = self.processes.get(server_id)
        if proc:
            proc.kill()

    def send_command(self, server_id: str, command: str) -> bool:
        proc = self.processes.get(server_id)
        if proc:
            return proc.send_command(command)
        return False

    def get_logs(self, server_id: str) -> List[str]:
        proc = self.processes.get(server_id)
        return proc.get_logs() if proc else []

    def get_stats(self, server_id: str) -> Dict[str, Any]:
        proc = self.processes.get(server_id)
        if proc:
            return proc.get_stats()
        return {
            "cpuPercent": 0.0,
            "memoryBytes": 0,
            "maxMemoryBytes": 0,
            "onlinePlayers": 0,
            "maxPlayers": 20,
            "uptimeSeconds": 0,
            "status": "offline",
        }

    # Properties
    def get_properties(self, server_id: str) -> Dict[str, str]:
        props_path = os.path.join(self.get_server_dir(server_id), "server.properties")
        return ServerProperties.read(props_path)

    def save_properties(self, server_id: str, updates: Dict[str, Any]):
        props_path = os.path.join(self.get_server_dir(server_id), "server.properties")
        ServerProperties.write(props_path, updates)

    # File Operations
    def list_files(self, server_id: str, sub_path: str = "") -> List[Dict[str, Any]]:
        base_dir = self.get_server_dir(server_id)
        target_dir = os.path.abspath(os.path.join(base_dir, sub_path.lstrip("/")))
        if not target_dir.startswith(base_dir):
            raise PermissionError("Access denied")

        if not os.path.exists(target_dir):
            return []

        entries = []
        for item in os.listdir(target_dir):
            full_path = os.path.join(target_dir, item)
            rel_path = os.path.relpath(full_path, base_dir)
            is_dir = os.path.isdir(full_path)
            stat = os.stat(full_path)
            entries.append({
                "name": item,
                "path": rel_path,
                "isDirectory": is_dir,
                "size": stat.st_size if not is_dir else 0,
                "modified": int(stat.st_mtime * 1000),
            })
        return sorted(entries, key=lambda x: (not x["isDirectory"], x["name"].lower()))

    def read_file(self, server_id: str, file_path: str) -> str:
        base_dir = self.get_server_dir(server_id)
        target = os.path.abspath(os.path.join(base_dir, file_path.lstrip("/")))
        if not target.startswith(base_dir):
            raise PermissionError("Access denied")
        with open(target, "r", encoding="utf-8", errors="replace") as f:
            return f.read()

    def write_file(self, server_id: str, file_path: str, content: str):
        base_dir = self.get_server_dir(server_id)
        target = os.path.abspath(os.path.join(base_dir, file_path.lstrip("/")))
        if not target.startswith(base_dir):
            raise PermissionError("Access denied")
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8") as f:
            f.write(content)

    def delete_file(self, server_id: str, file_path: str):
        base_dir = self.get_server_dir(server_id)
        target = os.path.abspath(os.path.join(base_dir, file_path.lstrip("/")))
        if not target.startswith(base_dir):
            raise PermissionError("Access denied")
        if os.path.isdir(target):
            shutil.rmtree(target)
        elif os.path.exists(target):
            os.remove(target)

    # Backups
    def create_backup(self, server_id: str, name: Optional[str] = None) -> str:
        server_dir = self.get_server_dir(server_id)
        backup_name = name or f"backup-{server_id}-{int(time.time())}.zip"
        backup_path = os.path.join(settings.backups_dir, backup_name)

        with zipfile.ZipFile(backup_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            for root, _, files in os.walk(server_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, server_dir)
                    zipf.write(file_path, arcname)

        return backup_name

server_manager = ServerManager()
