import os
from typing import Dict, Any

class ServerProperties:
    @staticmethod
    def read(props_path: str) -> Dict[str, str]:
        if not os.path.exists(props_path):
            return {}
        props: Dict[str, str] = {}
        with open(props_path, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or line.startswith("!"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    props[key.strip()] = val.strip()
        return props

    @staticmethod
    def write(props_path: str, updates: Dict[str, Any]):
        existing_lines = []
        existing_keys = set()

        if os.path.exists(props_path):
            with open(props_path, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    stripped = line.strip()
                    if stripped and not stripped.startswith("#") and not stripped.startswith("!") and "=" in stripped:
                        key, _ = stripped.split("=", 1)
                        key = key.strip()
                        if key in updates:
                            existing_lines.append(f"{key}={updates[key]}\n")
                            existing_keys.add(key)
                        else:
                            existing_lines.append(line)
                    else:
                        existing_lines.append(line)
        else:
            existing_lines.append("# Minecraft server properties generated by Warden\n")

        for key, val in updates.items():
            if key not in existing_keys:
                existing_lines.append(f"{key}={val}\n")

        with open(props_path, "w", encoding="utf-8") as f:
            f.writelines(existing_lines)
